//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game_items_selling_forms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Предметы_из_игр
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Предметы_из_игр()
        {
            this.Чек = new HashSet<Чек>();
        }
    
        public int Код_предмета { get; set; }
        public int Код_игры { get; set; }
        public string Название { get; set; }
        public string Буквенный_код_валюты { get; set; }
        public decimal Цена { get; set; }
        public string Редкость { get; set; }
        public int Количество { get; set; }
    
        public virtual Игры Игры { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Чек> Чек { get; set; }
        public virtual Валюты Валюты { get; set; }
    }
}
