//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game_items_selling_web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Game_items_tradingEntities : DbContext
    {
        public Game_items_tradingEntities()
            : base("name=Game_items_tradingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Валюты> Валюты { get; set; }
        public DbSet<Возрастной_рейтинг> Возрастной_рейтинг { get; set; }
        public DbSet<Жанры> Жанры { get; set; }
        public DbSet<Игры> Игры { get; set; }
        public DbSet<Издатели> Издатели { get; set; }
        public DbSet<Платформы> Платформы { get; set; }
        public DbSet<Предметы_из_игр> Предметы_из_игр { get; set; }
        public DbSet<Разработчики> Разработчики { get; set; }
        public DbSet<Страны> Страны { get; set; }
        public DbSet<Торговые_площадки> Торговые_площадки { get; set; }
        public DbSet<Чек> Чек { get; set; }
    }
}
