//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game_items_selling_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Издатели
    {
        public Издатели()
        {
            this.Игры = new HashSet<Игры>();
        }
    
        public int Код_издателя { get; set; }
        public string Издатель { get; set; }
        public string Код_страны { get; set; }
    
        public virtual Страны Страны { get; set; }
        public virtual ICollection<Игры> Игры { get; set; }
    }
}
