//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game_items_selling_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Предметы_из_игр
    {
        public Предметы_из_игр()
        {
            this.Чек = new HashSet<Чек>();
        }
    
        public int Код_предмета { get; set; }
        public int Код_игры { get; set; }
        public string Игровой_предмет { get; set; }
        public string Буквенный_код_валюты { get; set; }
        public decimal Цена { get; set; }
        public string Редкость { get; set; }
        public int Количество { get; set; }
    
        public virtual Валюты Валюты { get; set; }
        public virtual Игры Игры { get; set; }
        public virtual ICollection<Чек> Чек { get; set; }
    }
}
