//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game_items_selling_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Разработчики
    {
        public Разработчики()
        {
            this.Игры = new HashSet<Игры>();
        }
    
        public int Код_разработчика { get; set; }
        public string Разработчик { get; set; }
        public System.DateTime Дата_основания { get; set; }
        public int Кол_во_сотрудников { get; set; }
    
        public virtual ICollection<Игры> Игры { get; set; }
    }
}
