//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game_items_selling_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Страны
    {
        public Страны()
        {
            this.Издатели = new HashSet<Издатели>();
            this.Торговые_площадки = new HashSet<Торговые_площадки>();
        }
    
        public string Буквенный_код_страны { get; set; }
        public string Страна { get; set; }
    
        public virtual ICollection<Издатели> Издатели { get; set; }
        public virtual ICollection<Торговые_площадки> Торговые_площадки { get; set; }
    }
}
