//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game_items_selling_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Торговые_площадки
    {
        public Торговые_площадки()
        {
            this.Чек = new HashSet<Чек>();
        }
    
        public int Код_торговой_площадки { get; set; }
        public string Торговая_площадка { get; set; }
        public System.DateTime Дата_создания { get; set; }
        public string Код_страны { get; set; }
    
        public virtual Страны Страны { get; set; }
        public virtual ICollection<Чек> Чек { get; set; }
    }
}
